export default {
  CLOSE: "CLOSE",
  MAXIMIZE: "MAXIMIZE",
  MINIMIZE: "MINIMIZE",
  OPEN_KICK_PAGE: "OPEN_KICK_PAGE",
  GET_SETTINGS: "GET_SETTINGS",
  SET_SETTING: "SET_SETTING",
  SHOW_CONTEXT_MENU: "SHOW_CONTEXT_MENU",
  CONTEXT_MENU_COMMAND: "CONTEXT_MENU_COMMAND",
  REMOVE_CHANNEL: "REMOVE_CHANNEL",
  CLOSE_KICK_PAGE: "CLOSE_KICK_PAGE",
  OPEN_BROWSER: "OPEN_BROWSER",
} as const;
