name: Build/release

on:
    push:
      tags:        
        - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    outputs:
      output1: ${{ steps.changelog.outputs.changelog }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Exit if not on main branch
        if: endsWith(github.event.base_ref, 'main') == false
        run: exit -1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.2.0
        with:
          mytoken: ${{ secrets.GITHUB_TOKEN }}

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

  post-release:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Modify the changelog
        id: modified
        run: |
          set -o noglob
          log=$(cat << "EOF" | sed -E 's/\(([^)]+?)\)/<\1>/g' <<< ${{ needs.release.outputs.changelog }})
          log="${log//'%'/'%25'}"
          log="${log//$'\n'/'%0A'}"
          log="${log//$'\r'/'%0D'}"
          echo "log=$log" >> $GITHUB_OUTPUT
      - name: notify-discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.RELEASES_WEBHOOK_URL }}
          content: "# New Release ${{github.ref_name}}\nGet it here: [${{github.ref_name}}](https://github.com/vicodinee/kickerino/releases/tag/${{github.ref_name}})\n${{ steps.modified.outputs.log }}"
      - name: Publish storybook
        id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0