name: Build/release

on:
    push:
      tags:        
        - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    outputs:
      output1: ${{ steps.changelog.outputs.changelog }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    permissions:
      contents: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.GITHUB_TOKEN }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

  post-release:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          clean: true
          target-folder: docs
          clean-exclude: |
            .nojekyll
      - name: Publish changelog to Discord
        env:
          WEBHOOK_URL: ${{ secrets.RELEASES_WEBHOOK_URL }}
        run: npm run get-changelog ${{ github.ref_name }}
